spring:
  cloud:
    gateway:
      routes:
        - id: baidu_router
          uri: https://www.baidu.com/
          predicates:
            - Query=url,baidu

        - id: qq_router
          uri: https://www.qq.com
          predicates:
            - Query=url,qq